# Coder Helm Chart - Base
# Docs: https://coder.com/docs/install/kubernetes
# Chart: https://helm.coder.com/v2
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: coder
  namespace: coder
spec:
  chart: coder
  repo: https://helm.coder.com/v2
  targetNamespace: coder
  version: "2.30.0"
  valuesContent: |-
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
      service:
        type: LoadBalancer
        sessionAffinity: None
