apiVersion: v1
kind: Namespace
metadata:
  name: coder
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/managed-by: Helm
    managed-by: gitops
  annotations:
    meta.helm.sh/release-name: gitops-dev-prd-apps-coder
    meta.helm.sh/release-namespace: coder
