# CloudNativePG Cluster for Coder
# Pattern follows high-command-postgres in the cluster
# Requires: coder-postgres-credentials secret (username, password) in same namespace
#
# Connection URL for Coder:
#   postgres://{user}:{password}@coder-postgres-rw.coder:5432/coder?sslmode=disable
#
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-postgres
  namespace: coder
spec:
  instances: 1
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-postgres-credentials
  storage:
    size: 10Gi
    storageClass: truenas-nfs
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
