# CloudNativePG Cluster for Coder - 3 instances for HA
# Requires: coder-postgres-credentials secret (username, password) in same namespace
#
# Connection URL for Coder:
#   postgres://{user}:{password}@coder-postgres-rw.coder:5432/coder?sslmode=disable
#
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-postgres
  namespace: coder
spec:
  instances: 3
  # Omit fsGroup for NFS — kubelet applyFSGroup fails when initdb creates pgdata with 700.
  # With dataset 0777, postgres (UID 26) can access the volume directly.
  podSecurityContext:
    runAsUser: 26
    runAsGroup: 26
    runAsNonRoot: true
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-postgres-credentials
  storage:
    size: 10Gi
    storageClass: truenas-csi-nfs  # Cluster-level StorageClass (omit mapall + dataset 0777)
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
